---
all:
  children:
    radar_clients:
      hosts:
        tuxcare-lab:

    eportal:
      hosts:
        eportal-lab:
          ansible_host: 192.168.56.50
          ansible_user: ansible

    kernelcare:
      children:
        kernelcare_cloud:
          hosts:
            tuxcare-lab:
              ansible_connection: local
              ansible_host: 127.0.0.1
              ansible_python_interpreter: /usr/bin/python3

        kernelcare_eportal:
          hosts:
            linux-client-01:
              ansible_host: 192.168.56.61
              ansible_user: ansible
            linux-client-02:
              ansible_host: 192.168.56.62
              ansible_user: ansible
