---
- name: Configurar repositorio RPM do TuxCare Radar
  ansible.builtin.yum_repository:
    name: tuxcare-radar
    description: TuxCare Radar
    baseurl: "https://repo.tuxcare.com/radar/$releasever/$basearch/"
    enabled: true
    gpgcheck: true
    skip_if_unavailable: true
    gpgkey: "https://repo.tuxcare.com/radar/RPM-GPG-KEY-TuxCare"
    state: present

- name: Instalar pacote TuxCare Radar via DNF
  ansible.builtin.dnf:
    name: "{{ tuxcare_radar_package_name }}"
    state: present
    update_cache: true
