---
tuxcare_eportal_allowed_hosts: []
tuxcare_eportal_cache_mode: true
tuxcare_eportal_proxy_url: ""
tuxcare_eportal_admin_user: admin
tuxcare_eportal_admin_password: ""
tuxcare_eportal_registration_key: ""
tuxcare_eportal_registration_key_server_limit: 10
tuxcare_eportal_registration_key_feed: ""
