---
tuxcare_kernelcare_source: cloud
tuxcare_kernelcare_eportal_url: ""
tuxcare_kernelcare_activation_key: ""
tuxcare_kernelcare_registration_id: default
tuxcare_kernelcare_auto_update: true
tuxcare_kernelcare_apply_now: true
tuxcare_kernelcare_validate_certs: true
tuxcare_kernelcare_proxy_url: ""
tuxcare_kernelcare_sticky_patch_from_key: false
tuxcare_kernelcare_installer_path: /usr/local/src/kernelcare-installer.sh
tuxcare_kernelcare_marker_dir: /var/lib/tuxcare-ansible
tuxcare_kernelcare_marker_file: "{{ tuxcare_kernelcare_marker_dir }}/registration-id"
