---
- name: Instalar e configurar o servidor TuxCare ePortal
  hosts: eportal
  become: true
  gather_facts: true

  roles:
    - role: tuxcare_eportal
      vars:
        tuxcare_eportal_admin_password: "{{ vault_eportal_admin_password }}"
        tuxcare_eportal_registration_key: "{{ vault_eportal_registration_key }}"
